# Site config
defaults:
  - scope:
      path: "" # empty string means everywhere
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:slug
      layout: "post"
      published: false

author: "64b.it"
title: "64b.it | Software Development & Quality Consulting"
description: "Lower your maintenance costs, iterate faster, build software more efficiently."
repo: "https://github.com/coaxial/hello"
# Jekyll config
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
