# Site config
defaults:
  -
    scope:
      path: "" # empty string means everywhere
      type: "pages"
    values:
      layout: "default"

author: "Coaxial"
title: "Coaxial, software developer"
description: "Coaxial's personal website. Everything you ever wanted to know about me."
repo: "https://github.com/coaxial/hello"
# Jekyll config
theme: jekyll-theme-midnight
markdown: kramdown
include:
  - assets/vendor/font-awesome/fonts
exclude:
  - Gemfile
  - Gemfile.lock
