[build]
  command = 'make build'
  functions = 'functions'
  publish = '_site'
  environment = { AWS_LAMBDA_JS_RUNTIME = 'nodejs16.x' }
[dev]
  autoLaunch = true
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
