[build]
  command = 'make dist'
  functions = 'functions'
  publish = 'dist'
[context.production.environment]
  JEKYLL_ENV = 'production'
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true
[[plugins]]
  package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-minify-html"
[dev]
  autoLaunch = true
  command = 'jekyll serve --livereload --incremental --watch'
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
[[redirects]]
  # Serve Plausible as a first-party script
  from = "/js/ascript.js"
  to = "https://plausible.io/js/script.js"
  status = 200
[[redirects]]
  # Also proxy Plausible events
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
[[redirects]]
  from = '/*'
  to = '/woops'
  status = 404
